### ISSUE TITLE
How to add distributed load in UEL

### ISSUE THREAD

**Issue by daniallin** [irfancn/UEL-elastic#1]
Sorry to bother you, your project is great! I would like to ask, do you know how to implement distributed load in UEL? Many thanks.

**Comment by irfancn** [comment]
Easy way to do that is by creating a set of elements in the input file and defining the load.
The next way is to define the load inside the UEL, in the force and stiffness matrix. This would be efficient to implement any load distribution (such as force or pressure as a function). But this will require examining the elements and particular nodes beforehand. It would be easier to examine the nodes in matlab or something similar then load those in to the UEL.

**Comment by daniallin** [comment]
Thanks for your responses. I have created a set of elements and defined the load in the .inp file. And I updated the RHS matrix. But after these operations, the model no longer converges.......
I think my changes to the UEL file are wrong, but I don't know how to modify it correctly. If possible, could you give me an example of how to implement a distributed load in UEL (how to redefine the force and stiffness matrix)?  Thanks a million!

**Comment by daniallin** [comment]
Thanks! Maybe I should promise you some rewards, like citing your articles?

**Comment by abcdvemm** [comment]
but, how to visualize the odb file?

Best,
Libo Yan
